services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ai_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ai_website_memory
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_user -d ai_memory"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
