"""Initial commit with DB and indexed

Revision ID: 15c150151ed4
Revises: 57b132de810f
Create Date: 2026-02-04 10:08:10.621053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '15c150151ed4'
down_revision: Union[str, Sequence[str], None] = '57b132de810f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_last_active', 'users', ['last_active'], unique=False, postgresql_using='btree', postgresql_ops={'last_active': 'DESC'})
    op.create_index('idx_users_meta_data', 'users', ['meta_data'], unique=False, postgresql_using='gin')
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_sessions_started_at', 'sessions', ['started_at'], unique=False, postgresql_using='btree', postgresql_ops={'started_at': 'DESC'})
    op.create_index('idx_sessions_user_active', 'sessions', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_sessions_user_started', 'sessions', ['user_id', 'started_at'], unique=False, postgresql_using='btree', postgresql_ops={'started_at': 'DESC'})
    op.create_table('user_memories',
    sa.Column('memory_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('memory_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('memory_type', sa.String(length=50), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_index('idx_memories_created', 'user_memories', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_memories_embedding', 'user_memories', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_memories_meta_data', 'user_memories', ['meta_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_memories_user_type', 'user_memories', ['user_id', 'memory_type'], unique=False)
    op.create_table('session_messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('idx_messages_role', 'session_messages', ['role'], unique=False)
    op.create_index('idx_messages_session_created', 'session_messages', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_messages_session_turn', 'session_messages', ['session_id', 'turn_number'], unique=False)
    op.create_table('ui_cards_shown',
    sa.Column('card_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('card_type', sa.String(length=100), nullable=False),
    sa.Column('card_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('shown_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_index('idx_cards_data', 'ui_cards_shown', ['card_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_cards_session_turn', 'ui_cards_shown', ['session_id', 'turn_number'], unique=False)
    op.create_index('idx_cards_type', 'ui_cards_shown', ['card_type'], unique=False)
    op.create_table('user_facts',
    sa.Column('fact_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('fact_key', sa.String(length=255), nullable=False),
    sa.Column('fact_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('source_memory_id', sa.UUID(), nullable=True),
    sa.Column('first_mentioned', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_memory_id'], ['user_memories.memory_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fact_id')
    )
    op.create_index('idx_facts_updated', 'user_facts', ['last_updated'], unique=False, postgresql_using='btree', postgresql_ops={'last_updated': 'DESC'})
    op.create_index('idx_facts_user_category', 'user_facts', ['user_id', 'category'], unique=False)
    op.create_index('idx_facts_value', 'user_facts', ['fact_value'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_facts_value', table_name='user_facts', postgresql_using='gin')
    op.drop_index('idx_facts_user_category', table_name='user_facts')
    op.drop_index('idx_facts_updated', table_name='user_facts', postgresql_using='btree', postgresql_ops={'last_updated': 'DESC'})
    op.drop_table('user_facts')
    op.drop_index('idx_cards_type', table_name='ui_cards_shown')
    op.drop_index('idx_cards_session_turn', table_name='ui_cards_shown')
    op.drop_index('idx_cards_data', table_name='ui_cards_shown', postgresql_using='gin')
    op.drop_table('ui_cards_shown')
    op.drop_index('idx_messages_session_turn', table_name='session_messages')
    op.drop_index('idx_messages_session_created', table_name='session_messages')
    op.drop_index('idx_messages_role', table_name='session_messages')
    op.drop_table('session_messages')
    op.drop_index('idx_memories_user_type', table_name='user_memories')
    op.drop_index('idx_memories_meta_data', table_name='user_memories', postgresql_using='gin')
    op.drop_index('idx_memories_embedding', table_name='user_memories', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_memories_created', table_name='user_memories', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('user_memories')
    op.drop_index('idx_sessions_user_started', table_name='sessions', postgresql_using='btree', postgresql_ops={'started_at': 'DESC'})
    op.drop_index('idx_sessions_user_active', table_name='sessions')
    op.drop_index('idx_sessions_started_at', table_name='sessions', postgresql_using='btree', postgresql_ops={'started_at': 'DESC'})
    op.drop_table('sessions')
    op.drop_index('idx_users_meta_data', table_name='users', postgresql_using='gin')
    op.drop_index('idx_users_last_active', table_name='users', postgresql_using='btree', postgresql_ops={'last_active': 'DESC'})
    op.drop_table('users')
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
